export const ManageUsersStyles = {
    container: "space-y-6",
    header: "flex items-center justify-between",
    title: "text-2xl font-bold text-foreground",
    emptyState: "bg-white rounded-lg border border-gray-200 p-12 text-center",
    emptyIcon: "text-gray-400 text-6xl mb-4",
    emptyTitle: "text-lg font-medium text-gray-900 mb-2",
    emptyMessage: "text-gray-500 mb-4",
    emptyButton: "px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors duration-200 text-sm font-medium",
    tableContainer: "bg-white rounded-lg border border-gray-200 overflow-hidden",
    table: "w-full",
    tableHead: "bg-gray-50",
    tableHeader: "px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider",
    tableBody: "bg-white divide-y divide-gray-200",
    tableRow: "hover:bg-gray-50",
    tableCellName: "px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 text-center",
    tableCellEmail: "px-6 py-4 whitespace-nowrap text-sm text-gray-500 text-center",
    tableCellItems: "px-6 py-4 text-sm text-gray-500 text-center",
    itemsContainer: "space-y-1",
    itemText: "text-xs",
    tableCellActions: "px-6 py-4 whitespace-nowrap text-sm font-medium text-center",
    editButton: "text-blue-600 hover:text-blue-900 transition-colors duration-200",
    paginationContainer: "flex items-center justify-between",
    paginationControls: "flex items-center space-x-2",
    paginationButton: "px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200",
    paginationButtonDisabled: "bg-gray-100 text-gray-400 cursor-not-allowed",
    paginationButtonActive: "bg-white text-gray-700 hover:bg-gray-50 border border-gray-300",
    paginationText: "text-sm text-gray-500"
};

