export const ManageUsersStyles = {
    container: "bg-white rounded-lg shadow",
    header: "p-4 md:p-6 border-b border-gray-200",
    title: "text-xl md:text-2xl font-bold text-gray-900",
    emptyState: "flex flex-col items-center justify-center py-8 md:py-12 px-4",
    emptyIcon: "text-4xl md:text-6xl mb-4",
    emptyTitle: "text-lg md:text-xl font-semibold text-gray-900 mb-2",
    emptyMessage: "text-sm md:text-base text-gray-600 text-center max-w-md",
    emptyButton: "mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors text-sm md:text-base",
    tableContainer: "overflow-x-auto",
    table: "min-w-full divide-y divide-gray-200",
    tableHead: "bg-gray-50",
    tableHeader: "px-3 md:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider",
    tableBody: "bg-white divide-y divide-gray-200",
    tableRow: "hover:bg-gray-50",
    tableCellName: "px-3 md:px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900",
    tableCellEmail: "px-3 md:px-6 py-4 whitespace-nowrap text-xs md:text-sm text-gray-600",
    tableCellItems: "px-3 md:px-6 py-4",
    itemsContainer: "flex flex-wrap gap-1 md:gap-2",
    itemText: "inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800",
    tableCellActions: "px-3 md:px-6 py-4 whitespace-nowrap text-right text-sm font-medium",
    editButton: "text-blue-600 hover:text-blue-900 text-xs md:text-sm",
    paginationContainer: "px-4 md:px-6 py-4 border-t border-gray-200",
    paginationControls: "flex flex-col md:flex-row items-center justify-between gap-2 md:gap-0",
    paginationButton: "px-3 md:px-4 py-2 border rounded-md text-xs md:text-sm font-medium",
    paginationButtonActive: "text-gray-700 bg-white border-gray-300 hover:bg-gray-50",
    paginationButtonDisabled: "text-gray-400 bg-gray-100 border-gray-200 cursor-not-allowed",
    paginationText: "text-xs md:text-sm text-gray-700"
};
