export const BillingsStyles = {
  title: "text-2xl font-bold text-foreground",
  container: "mt-6 space-y-6",
  sectionCard: "bg-white rounded-xl shadow-sm border border-gray-200 p-6",
  sectionTitle: "text-xl font-semibold text-foreground mb-4",
  sectionDescription: "text-muted-foreground mb-6",
  trendingGrid: "grid grid-cols-1 md:grid-cols-3 gap-6",
  trendingCard: "text-center",
  trendingCardInner: "bg-gray-100 rounded-lg p-6 mb-3",
  productName: "text-lg font-semibold text-gray-900 mb-3",
  productImageContainer: "flex justify-center mb-3",
  productImage: "w-16 h-16 object-contain",
  purchaseCountBadge: "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800",
  emptyState: "text-center py-8",
  emptyStateIcon: "text-4xl mb-2",
  emptyStateText: "text-muted-foreground",
  emptyStateSubtext: "text-sm text-muted-foreground mt-1",
  loadingContainer: "flex flex-col items-center justify-center py-12",
  loadingSpinner: "w-12 h-12 border-4 border-gray-200 border-t-blue-500 rounded-full animate-spin",
  loadingText: "mt-4 text-gray-500",
  tableContainer: "overflow-x-auto",
  table: "min-w-full divide-y divide-gray-200",
  tableHead: "bg-gray-50",
  tableHeader: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider",
  tableBody: "bg-white divide-y divide-gray-200",
  tableRow: "hover:bg-gray-50",
  tableCell: "px-6 py-4 whitespace-nowrap text-sm text-gray-900",
  tableCellBold: "px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900",
  statusBadge: "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800",
  paginationContainer: "flex items-center justify-between mt-6",
  paginationInfo: "text-sm text-gray-700",
  paginationButtons: "flex",
  paginationButton: "px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed",
  paginationButtonPrev: "px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-l-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed",
  paginationButtonNext: "px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-r-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed",
  paginationButtonActive: "px-3 py-2 text-sm font-medium border-t border-b bg-blue-50 border-blue-500 text-blue-600",
  paginationButtonInactive: "px-3 py-2 text-sm font-medium border-t border-b bg-white border-gray-300 text-gray-500 hover:bg-gray-50",
};

