export const BillingsStyles = {
  title: "text-xl md:text-2xl font-bold text-foreground",
  container: "mt-4 md:mt-6 space-y-4 md:space-y-6",
  sectionCard: "bg-white rounded-xl shadow-sm border border-gray-200 p-4 md:p-6",
  sectionTitle: "text-lg md:text-xl font-semibold text-foreground mb-3 md:mb-4",
  sectionDescription: "text-sm md:text-base text-muted-foreground mb-4 md:mb-6",
  trendingGrid: "grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6",
  trendingCard: "text-center",
  trendingCardInner: "bg-gray-100 rounded-lg p-4 md:p-6 mb-2 md:mb-3",
  productName: "text-base md:text-lg font-semibold text-gray-900 mb-2 md:mb-3",
  productImageContainer: "flex justify-center mb-2 md:mb-3",
  productImage: "w-12 h-12 md:w-16 md:h-16 object-contain",
  purchaseCountBadge: "inline-flex items-center px-2 md:px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800",
  emptyState: "text-center py-6 md:py-8 px-4",
  emptyStateIcon: "text-3xl md:text-4xl mb-2",
  emptyStateText: "text-sm md:text-base text-muted-foreground",
  emptyStateSubtext: "text-xs md:text-sm text-muted-foreground mt-1",
  loadingContainer: "flex flex-col items-center justify-center py-8 md:py-12",
  loadingSpinner: "w-10 h-10 md:w-12 md:h-12 border-4 border-gray-200 border-t-blue-500 rounded-full animate-spin",
  loadingText: "mt-3 md:mt-4 text-sm md:text-base text-gray-500",
  tableContainer: "overflow-x-auto -mx-4 md:mx-0",
  table: "min-w-full divide-y divide-gray-200",
  tableHead: "bg-gray-50",
  tableHeader: "px-3 md:px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider",
  tableBody: "bg-white divide-y divide-gray-200",
  tableRow: "hover:bg-gray-50",
  tableCell: "px-3 md:px-6 py-3 md:py-4 whitespace-nowrap text-xs md:text-sm text-gray-900",
  tableCellBold: "px-3 md:px-6 py-3 md:py-4 whitespace-nowrap text-xs md:text-sm font-medium text-gray-900",
  statusBadge: "inline-flex items-center px-2 md:px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800",
  paginationContainer: "flex flex-col md:flex-row items-center justify-between mt-4 md:mt-6 gap-3 md:gap-0 px-4 md:px-0",
  paginationInfo: "text-xs md:text-sm text-gray-700 order-2 md:order-1",
  paginationButtons: "flex flex-wrap justify-center gap-1 order-1 md:order-2",
  paginationButton: "px-2 md:px-3 py-1.5 md:py-2 text-xs md:text-sm font-medium text-gray-500 bg-white border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed",
  paginationButtonPrev: "px-2 md:px-3 py-1.5 md:py-2 text-xs md:text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-l-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed",
  paginationButtonNext: "px-2 md:px-3 py-1.5 md:py-2 text-xs md:text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-r-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed",
  paginationButtonActive: "px-2 md:px-3 py-1.5 md:py-2 text-xs md:text-sm font-medium border-t border-b bg-blue-50 border-blue-500 text-blue-600",
  paginationButtonInactive: "px-2 md:px-3 py-1.5 md:py-2 text-xs md:text-sm font-medium border-t border-b bg-white border-gray-300 text-gray-500 hover:bg-gray-50",
};

